CREATE TABLE pending_signup (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('USER', 'TECHNICIAN', 'ADMIN') NOT NULL,
    created_at DATETIME NOT NULL
);
