
ALTER TABLE ServiceRequests
    MODIFY status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

ALTER TABLE Technicians
    MODIFY status ENUM('PENDING', 'APPROVED', 'REJECTED', 'BLOCKED') NOT NULL;

ALTER TABLE Users
    MODIFY phone VARCHAR(15) NOT NULL;

ALTER TABLE Technicians
    MODIFY phone VARCHAR(15) NOT NULL;

ALTER TABLE AdminActions
    MODIFY target_type ENUM('USER', 'TECHNICIAN') DEFAULT NULL;

ALTER TABLE Technicians
DROP COLUMN skills;

CREATE TABLE Skills (
    skill_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE TechnicianSkills (
    tech_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    PRIMARY KEY (tech_id, skill_id),
    FOREIGN KEY (tech_id) REFERENCES Technicians(tech_id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES Skills(skill_id) ON DELETE CASCADE
);
